contentful/contentful-import

- lib/usageParams.js
This PR adds the possibility to specify the API host, this is useful for example if we want to test against staging for example.
The property `managementHost` is coming from [here](https://github.com/contentful/contentful-batch-libs/blob/master/lib/utils/create-clients.js#L40)
> feat(contentful-import): Add api host option

- README.md
- lib/get-transformed-destination-response.js
- lib/index.js
- lib/usageParams.js
We are accidentally missing the `contentModelOnly` flag to make `skipLocales` work.
> fix skipping of locales by introducing flag for content model only

- lib/parseOptions.js
When the json is changed manually and one of the arrays that the tool is expecting is removed the tool will crash, this PR fixes that
> fix(parseOption): handle non existing lists

- lib/utils/proxy.js
[`options.httsAgent`](https://github.com/contentful/contentful-import/blob/master/lib/parseOptions.js#L69) needs to be an `httpsAgent` and not a `{httpsAgent: agent}` object
> fix(proxy): Fix httpsAgent Creation

- lib/index.js
- package.json
* Integrates the new push to space which uses lister for proper displaying
* shows a result table with actually imported entities instead of a fake one
* bugfixes (within the batch-libs)
> push to space

- lib/parseOptions.js
I experienced some problems when trying to duplicate all my stuff from one space to another using `contentful-export` and `contentful-import`.
Specifically, the export went well, but the import didn't recognize the data in my json dump, yielding a successful import of zero entities of every entity type.
See this gist for the output of `contentful-import`:
https://gist.github.com/ewendel/db9a67b3a6a38104891be68b70a7ca7c
After some digging, I find that these lines are the culprit:
```
// Clean up content to only include supported entity types
Object.keys(options.content).forEach(function (type) {
if (!SUPPORTED_ENTITY_TYPES.indexOf(type) >= 0) {
delete options.content[type];
}
});
```
`!SUPPORTED_ENTITY_TYPES.indexOf(type) >= 0` evaluates to true for all entity types on my system, hence …
> Fix logical error in parseOptions.js

- lib/index.js
We did log the error log twice and errorLog still contained warnings. This PR fixes this.
> fix(error-log): do not display log twice and throw only errors

- package.json
This Pull request removes the warning when the tool is installed as a dependency
> fix: Remove warning on install

- README.md
- lib/transform/transformers.js
- test/unit/transform/transformers.test.js
For security reasons, the value of secret headers are not exported with webhooks. This was causing an invalid webhook body on the import (and a 500 error). The fix is to exclude secret headers from the import.
> fix(webhooks): exclude secret headers

- lib/tasks/push-to-space/publishing.js
bug: if `entitiesToArchive` was > 1 item long, it would attempt to archive the first item n times, resulting in errors.
> Iterate over each entry in entriesToArchive

- lib/index.js
- lib/usageParams.js
I remove the `noUpdate` option for import, because it has never been implemented.
> doc(import): remove noUpdate

- README.md
- lib/index.js
- lib/parseOptions.js
- lib/tasks/get-destination-data.js
- lib/tasks/push-to-space/creation.js
- lib/tasks/push-to-space/push-to-space.js
- lib/transform/transform-space.js
- lib/transform/transformers.js
- lib/utils/schema.js
- package-lock.json
- package.json
- test/integration/sample-space.json
- test/unit/__snapshots__/validations.test.js.snap
- test/unit/index.test.js
- test/unit/parseOptions.test.js
- test/unit/tasks/get-destination-data.test.js
- test/unit/tasks/push/push-to-space.test.js
- test/unit/transform/transform-space.test.js
- test/unit/validations.test.js
This adds the ability to import tags into a space (if the tags feature is enabled on the space).
I went through each step in the import and added the tags entity: fetch destination data, transform entities, push to space. Some notes:
* for other entities, we fetch only the IDs that are included in the source import data (in batches). This is to check if the entity exists already and needs to be updated, or if it needs to be created. The tags API does not have the ability to fetch specific ids (no support for queries like `.../tags?sys.id[in]=tagid` ), and has a very low limit (100 total tags), so I simply fetch all destination tags in one call without batches or pagination. 
* we learn already in the "fetch destination data" step whether a space has the tags feature enabled. We catch …
> feat(tags): import tags entity

- lib/index.js
- lib/transform/transform-space.js
- lib/transform/transformers.js
- test/unit/transform/transformers.test.js
This PR fixes a [reported issue](https://github.com/contentful/contentful-import/issues/251) where an import with metadata tags fails on a space with tags feature not activated yet.
In this case the import would always fail. This fix checks for tags being present in remote data, to detect tags enablement.
For spaces without tags being enabled, we strip metadata tags from every entity before importing.
> fix(import): check for tags enabled

- lib/utils/schema.js
- test/unit/utils/schema.test.js
This fix allows the usage of JSON placeholders in webhook urls.
fixes #369 and https://github.com/contentful/contentful-cli/issues/577
> fix(webhooks): url validation

- lib/utils/schema.js
- test/unit/utils/schema.test.js
As we support [webhooks with multiple placeholder](https://github.com/contentful/webhook_consumer/blob/326efa7a5377c56eb7a887a5b1c44c0342ae92a7/lib/request/request-options/transform-request.spec.js#L38) in the BE, the import tool should do so as well.
> fix(webhooks): support multiple placeholders [ZEND-1275]

- test/unit/parseOptions.test.js
PR is to adjust regex path separators into a more cross platform solution. This copies the work done on the contentful-export project: https://github.com/contentful/contentful-export/pull/945/files
> fix(test): modify unit tests to handle x-platform regex matching

- babel.config.json
- package-lock.json
- package.json
Updates the babel config with the same configuration as that found in the contentful-export tool.
> chore(build): add babel preset-env

- .gitignore
- lib/index.js
- lib/parseOptions.js
- lib/tasks/get-destination-data.js
- package-lock.json
- package.json
- test/unit/parseOptions.test.js
Parsing large input files (> 512 MB) caused `JSON.parse` to throw an error:
```
Error: Cannot create a string longer than 0x1fffffe8 characters
```
this is a node internal hard limit for parsing strings to objects. 
This PR introduces a streaming library to allow bigger input files.
> fix: parsing of large files > 512 MB [ZEND-3117]

- lib/utils/sort-locales.js
- test/unit/sort-locales.test.js
Aims to fix [this issue](https://github.com/contentful/contentful-cli/issues/2170).
See issue description for all the details.
> fix: use null and not undefined as fallback code values for locales [PHX-2767]

- .eslintrc.js
- lib/index.ts
- package-lock.json
- package.json
- tsconfig.json
[This](https://github.com/contentful/contentful-import/pull/880) broke support for common js, this PR fixes it (see the long comment)
- adds tsup as bundler
- run tests synchronously as some of their processes were interfering with each other
> feat: add tsup and workaround to export both esm and cjs

- package.json
After the TS migration, [`usageParams.ts`](https://github.com/contentful/contentful-import/blob/master/lib/usageParams.ts) is not part of the bundle, and therefore can not be imported [here](https://github.com/contentful/contentful-import/blob/master/bin/contentful-import#L3). The change adds it as additiuonal entry point for the bundler to ensure it get's exported.
> fix: execution as CLI [NONE]

- lib/index.ts
see https://github.com/cli-table/cli-table3/blob/master/basic-usage.md#basic-usage---disable-colors---used-often-in-the-examples-and-tests and https://github.com/contentful/contentful-export/pull/1711
> fix: remove ANSI color codes from table output for better CI/CD compat [ZEND-4747]

- package.json
This fixes issue #955, "Error: Module not found: Error: Default condition should be last one".
I haven't created an open source PR before, so I apologize if I haven't gotten something quite right.  There is very little info in the contributing guidelines.
> fix: default should be last in exports

- README.md
Add instructions in the `Troubleshooting` section for how to use `contentful-export` and `contentful-import` with embargoed assets. See equivalent PR in `contentful-export` here: https://github.com/contentful/contentful-export/pull/2037
> chore: update README with embargoed asset info [DX-63]
