contentful/contentful-import

lib/run-contentful-import.js
package.json

You are definitely not going to want to merge this P/R...  However; once this P/R has been merged:
https://github.com/contentful/contentful-batch-libs/pull/80
and appropriate version bumped in package.json
I will update the `contentful-import` repo to utilize the changes from `contentful-batch-libs` so that no changes are made to the package.json.

Example for consuming new option `assetProcessDelay`

---

bin/contentful-import
lib/index.js
package.json
yarn.lock

Besides adding the info table and a duration at the end, it tries to do implement a proper usage of `npmlog`

Add info table about what to import and duration

---

package.json

Adding this feature https://github.com/contentful/contentful-batch-libs/pull/107

feat(createClient): enable headers config

---

README.md
lib/index.js
lib/parseOptions.js
lib/usageParams.js
package.json
yarn.lock

add proxy support

---

lib/parseOptions.js

fixes https://github.com/contentful/contentful-import/issues/40

fix(parseOptions): Setting content before webhooks

---

package.json

Including these fixes
https://github.com/contentful/contentful-batch-libs/pull/116
and 
https://github.com/contentful/contentful-batch-libs/pull/115

fix(import): Fix draft imports and entries creation

---

.gitignore
test/proxy-test.js

test(proxy): Add proxy test

---

lib/index.js
lib/usageParams.js
package.json

feat: Add noUpdate

---

.gitignore
lib/index.js
lib/utils/validations.js
test/unit/index-test.js

This PR adds an assert for default locales between destination space and source space.
the import tool will stop importing and tell you to change the default locale if they don't match.

feat: Add default locale check

---

package.json

Security update for moment: 
https://nodesecurity.io/advisories/532

fix: update moment

---

lib/index.js
lib/transform/transform-space.js
test/unit/index.test.js
test/unit/transform/transform-space.test.js

Promises were never used in the transformers. This PR removes them.

remove promises from transformers

---

lib/index.js
lib/parseOptions.js
lib/tasks/get-destination-data.js
lib/tasks/push-to-space/creation.js
lib/tasks/push-to-space/push-to-space.js
lib/usageParams.js
package.json
test/unit/tasks/get-destination-data.test.js
test/unit/tasks/push/creation.test.js
test/unit/tasks/push/push-to-space.test.js

This PR adds support for the environment API.

Add Environment support

---

lib/utils/schema.js
test/unit/validations.test.js

fix: fix webhook validation

---

.gitignore
package-lock.json
package.json

Updated `contentful-batch-libs` containing `https-proxy-agent` dependency due to [vulnerability](https://www.npmjs.com/advisories/1184).

fix(dependency): Update https-proxy-agent dependency

---

lib/tasks/push-to-space/creation.js
test/unit/tasks/push/creation.test.js

fix(creation): use correct error information (#127)

---

lib/tasks/push-to-space/creation.js
test/unit/tasks/push/creation.test.js

Ensure that tag visibility is preserved

fix: preserve tag visibility

---

lib/tasks/push-to-space/push-to-space.js

Handle group setting in editor interface import

feat: support groups settings

---

package-lock.json
package.json

Updates contentful-batch-libs to latest to fix date-fns issue

chore(deps): update contentful-batch-libs to v9.4.1

---

.circleci/config.yml
.contentful/vault-secrets.yaml
.github/workflows/dependabot-approve-and-request-merge.yml

Made everything one PR because the only change is when releasing. So no need for the two steps

feat: use vault secrets [SDK-2258]

---

README.md

I wasn't sure if the package would work using ESM because there was mention of it in the readme. It does! 
This PR updates the readme to show how to import the package using ESM

Updated readme to add ESM example

---

lib/parseOptions.ts
lib/usageParams.ts
tsconfig.json

move parseOptions and usageParams to ts and adjust json import

chore(ts): move parseOptions and usageParams to ts and adjust json import [PHX-2879]

---

lib/tasks/push-to-space/assets.ts
lib/tasks/push-to-space/creation.ts
lib/tasks/push-to-space/publishing.ts
lib/tasks/push-to-space/push-to-space.ts
lib/utils/errors.ts
tsconfig.json

- This mainly adjusts some type issues around expectations of error objects.

chore(ts): set strict to true in tsconfig and adjust accordingly

---

README.md
lib/index.ts
test/unit/index.test.ts

This adds publicly available and enforced ts interfaces to `runContentfulImport`.
- Fix ts errors in tests (params partly don't match my docs derived ts expectations) ✅ 
- Expand readme with missing params (see comment) ✅

feat(ts): add public ts types

---

.gitignore
lib/tasks/push-to-space/push-to-space.ts
test/integration/exports/with-custom-editor-interface/custom-editor-interface.json
test/integration/import-lib.test.ts

Respect more EditorInterface props when importing.  Adds `sidebar` and `editors` to import routine. 
Solves #599

feat: import sidebar configuration [ZEND-4192]

---

lib/transform/transformers.ts
package-lock.json
package.json
test/unit/transform/transformers.test.ts

Bulk updating for some vulnerable (dev) dependencies.

chore: fix vulnerable dependencies [NONE]

---

.circleci/config.yml

semantic-release requires node 20...

fix: use node 20 for release step in CI

---

lib/tasks/get-destination-data.ts
test/unit/tasks/get-destination-data.test.ts

fetch all tags in destination env

fix: fetch all tags [ZEND-5557]
